# Generated by Django 4.2.7 on 2023-11-28 19:59

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "About",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "contact",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("long_description", models.CharField(max_length=255)),
                ("short_description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to=app.models.image_filename)),
            ],
            options={
                "verbose_name_plural": "headers",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Results",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="WhyWe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("num_company", models.IntegerField()),
                ("students", models.IntegerField()),
                ("experiences", models.IntegerField()),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
                ("image", models.ImageField(upload_to=app.models.image_filename)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Why We",
            },
        ),
        migrations.CreateModel(
            name="ServiceChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_children",
                        to="app.service",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Children",
            },
        ),
        migrations.CreateModel(
            name="ResultChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app.result",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ResultChildren",
            },
        ),
    ]
